# Generated by Django 3.0 on 2021-08-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_fretes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefretes',
            old_name='hc40h',
            new_name='hc40',
        ),
    ]
