# Generated by Django 3.0 on 2021-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacoes',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Cadastro'),
        ),
    ]
