# Generated by Django 3.0 on 2021-09-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_cotacoes_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacoes',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='cmmdty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='demurrage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='detention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='dv20',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='dv40',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='hc40',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='pod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='pol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoes',
            name='quotation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
