# Generated by Django 3.0 on 2021-08-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_departamentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='empresa',
            new_name='Escritorio',
        ),
    ]
