# Generated by Django 3.0 on 2021-08-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20210824_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Escritorio',
            new_name='escritorio',
        ),
    ]
