# Generated by Django 3.0 on 2021-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('funcionarios', '0004_auto_20210824_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='escritorio',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escritorio',
            field=models.ManyToManyField(to='escritorios.Escritorio'),
        ),
    ]
