# Generated by Django 3.0 on 2021-08-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('funcionarios', '0005_auto_20210827_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='escritorio',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escritorios.Escritorio'),
        ),
    ]
