# Generated by Django 3.0 on 2021-08-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControleVazios',
            new_name='Filial',
        ),
    ]
