# Generated by Django 3.0 on 2021-08-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210824_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filial',
            new_name='Escritorio',
        ),
        migrations.AlterModelOptions(
            name='escritorio',
            options={'verbose_name_plural': 'Escritório'},
        ),
        migrations.RenameField(
            model_name='escritorio',
            old_name='nome_filial',
            new_name='nome_escritorio',
        ),
    ]
