# Generated by Django 3.0 on 2021-09-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210824_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Escritorio',
        ),
    ]
