# Generated by Django 3.0 on 2021-08-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escritorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escritorios.Escritorio')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
