# Generated by Django 3.0 on 2021-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleVazios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_booking', models.CharField(max_length=255)),
                ('pol_pod', models.CharField(max_length=255)),
                ('navio', models.CharField(max_length=255)),
                ('eta', models.CharField(max_length=255)),
                ('armador', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Vazio', 'Vazio'), ('Vendido', 'Vendido')], max_length=10)),
                ('cotacao', models.CharField(max_length=255)),
                ('observacoes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ControleVazios',
            },
        ),
    ]
