# Generated by Django 3.0 on 2021-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vazios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlevazios',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='ETA'),
        ),
    ]
