# Generated by Django 3.0 on 2021-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vazios', '0002_auto_20210813_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlevazios',
            old_name='pol_pod',
            new_name='pod',
        ),
        migrations.AddField(
            model_name='controlevazios',
            name='pol',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
