# Generated by Django 3.0 on 2021-08-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vazios', '0004_controlevazios_cmmdty'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlevazios',
            name='contrato_venda',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlevazios',
            name='shipper',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
