# Generated by Django 3.0 on 2021-08-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vazios', '0005_auto_20210817_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevazios',
            name='armador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='cmmdty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='contrato_venda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='cotacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='navio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='number_booking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='pod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='pol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='shipper',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlevazios',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
