# Generated by Django 3.0 on 2021-08-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_booking', models.CharField(blank=True, max_length=255, null=True)),
                ('pol', models.CharField(blank=True, max_length=255, null=True)),
                ('pod', models.CharField(blank=True, max_length=255, null=True)),
                ('navio', models.CharField(blank=True, max_length=255, null=True)),
                ('cmmdty', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('armador', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Vazio', 'Vazio'), ('Vendido', 'Vendido')], max_length=10)),
                ('cotacao', models.CharField(blank=True, max_length=255, null=True)),
                ('shipper', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato_venda', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cadastrado_Por_Por', to=settings.AUTH_USER_MODEL)),
                ('vendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vendido_Por_Por', to=settings.AUTH_USER_MODEL)),
                ('vendido_por_filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vendido_Por_Filial_Por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
    ]
