# Generated by Django 3.0 on 2021-08-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Escritório', to='escritorios.Escritorio'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_booking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº. Booking'),
        ),
    ]
