# Generated by Django 3.0 on 2021-08-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210825_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cmmdty',
            new_name='commodity',
        ),
    ]
