# Generated by Django 3.0 on 2021-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_escritorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Cadastro'),
        ),
        migrations.AddField(
            model_name='booking',
            name='data_venda',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Venda'),
        ),
    ]
