# Generated by Django 3.0 on 2021-09-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('booking', '0005_auto_20210907_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vendido_por_filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vendido_Por_Filial_Por', to='escritorios.Escritorio'),
        ),
    ]
