# Generated by Django 3.0 on 2021-09-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210908_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vendido_por_filial',
            new_name='escritorio',
        ),
    ]
