# Generated by Django 3.0 on 2021-09-08 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210908_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data do Cadastro'),
        ),
    ]
