# Generated by Django 3.0 on 2021-09-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('booking', '0008_auto_20210908_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='escritorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Escritório', to='escritorios.Escritorio'),
            preserve_default=False,
        ),
    ]
