# Generated by Django 3.0 on 2021-09-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
        ('booking', '0011_auto_20210908_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='escritorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vendido_Por_Filial_Por', to='escritorios.Escritorio'),
        ),
    ]
