# Generated by Django 3.0 on 2021-09-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210908_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ddl_draft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
