# Generated by Django 3.0 on 2021-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_ddl_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ddl_draft',
        ),
        migrations.AddField(
            model_name='booking',
            name='data_ddl_draft',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hora_ddl_draft',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
