# Generated by Django 3.0 on 2021-10-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0003_auto_20210907_0930'),
        ('booking', '0015_auto_20210920_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cotacoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cotacoes.Cotacoes'),
        ),
    ]
